"""PROTOTYPE: deterministic local HTTP corpus, references and environment inventory."""
import hashlib
import html
import importlib.metadata as md
import json
import os
from pathlib import Path
import platform
import winreg

ROOT = Path(__file__).resolve().parent
FIX = ROOT / 'fixtures'
BASE = 'http://127.0.0.1:8767'
RAPID_COMMIT = '4a3070f304467e6d426e78a82afea5cb1181f305'


def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding='utf-8')


def sha(data):
    return hashlib.sha256(data).hexdigest()


def main():
    from PIL import Image, ImageDraw, ImageFont
    from reportlab.pdfgen import canvas
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont
    from pypdf import PdfReader, PdfWriter
    import psutil
    import yaml
    FIX.mkdir(exist_ok=True)
    pdfmetrics.registerFont(UnicodeCIDFont('STSong-Light'))
    corpus = []
    refs = {
        'en': ['CPU Reading Experiment', 'Invoice ID: AX-2026-0917',
               'Total amount: 12345.67 USD', 'Windows and ONNX Runtime process local text.',
               'The final keyword is ORCHID.'],
        'zh': ['中文网页读取实验', '订单编号：京东20260917', '总金额：12345.67元',
               '北京、上海与深圳使用本机处理公开原文。', '最后的关键词是兰花。'],
    }
    font_path = Path(os.environ.get('WINDIR', 'C:/Windows')) / 'Fonts/msyh.ttc'
    font = ImageFont.truetype(str(font_path), 36)
    font_hash = sha(font_path.read_bytes())

    def add(name, kind, lang, ext, **extra):
        corpus.append(dict(id=name, kind=kind, language=lang, url=f'{BASE}/{name}.{ext}',
                           source='controlled fixture generated by prepare.py',
                           reference='\n'.join(refs[lang]), reference_scope='whole_unit',
                           keywords=['AX-2026-0917', '12345.67', 'ORCHID'] if lang == 'en'
                           else ['京东20260917', '12345.67', '兰花'], **extra))

    for lang, lines in refs.items():
        im = Image.new('RGB', (1400, 420), 'white')
        draw = ImageDraw.Draw(im)
        for i, line in enumerate(lines):
            draw.text((40, 35 + i * 72), line, font=font, fill='black')
        im.save(FIX / f'image-{lang}.png')
        add(f'image-{lang}', 'image', lang, 'png')
        for name, pages, mixed in [(f'scan-{lang}', 2, False),
                                   (f'text-{lang}', 2, True)]:
            c = canvas.Canvas(str(FIX / f'{name}.pdf'), pagesize=(700, 500), invariant=1)
            for _ in range(pages):
                if mixed:
                    c.setFont('STSong-Light' if lang == 'zh' else 'Helvetica', 18)
                    for i, line in enumerate(lines):
                        c.drawString(20, 460-i*50, line)
                else:
                    c.drawImage(str(FIX/f'image-{lang}.png'), 0, 230, width=700, height=210)
                c.showPage()
            c.save()
            add(name, 'pdf', lang, 'pdf', expected_pages=pages, expected_mode='text_layer' if mixed else 'ocr')
        article = '<article><h1>' + lines[0] + '</h1><h2 id="details">Details</h2>'
        article += ''.join(f'<p>{html.escape(line)}</p>' for line in lines[1:]) + '</article>'
        static = f'<!doctype html><meta charset="utf-8"><title>Reading {lang}</title><nav>NOISE_NAV menu login</nav>{article}<footer>NOISE_FOOTER</footer>'
        (FIX/f'html-{lang}.html').write_text(static, encoding='utf-8')
        add(f'html-{lang}', 'html', lang, 'html', reference_scope_override='contains_lines')
        dynamic = '<!doctype html><meta charset="utf-8"><title>JS only</title><main id="app">Loading</main><script>'
        dynamic += 'setTimeout(()=>{document.querySelector("main").innerHTML=' + json.dumps(article, ensure_ascii=False) + ';},150)</script>'
        (FIX/f'js-{lang}.html').write_text(dynamic, encoding='utf-8')
        add(f'js-{lang}', 'js', lang, 'html', ready_selector='article h1', reference_scope_override='contains_lines')
        inline = '<!doctype html><meta charset="utf-8"><title>Image article</title><article><h1>Image evidence</h1><p>Text is in the image below.</p>'
        inline += f'<img loading="lazy" src="/image-{lang}.png" alt="receipt"><p>End of image evidence.</p></article>'
        (FIX/f'inline-{lang}.html').write_text(inline, encoding='utf-8')
        add(f'inline-{lang}', 'inline', lang, 'html', reference_scope_override='image_unit')

    for name, image in [('rotated-zh', Image.open(FIX/'image-zh.png').rotate(90, expand=True)),
                        ('lowres-en', Image.open(FIX/'image-en.png').resize((350, 105)))]:
        image.save(FIX/f'{name}.png')
        add(name, 'image', 'zh' if name.endswith('zh') else 'en', 'png')
    columns = Image.new('RGB', (1400, 500), 'white')
    d = ImageDraw.Draw(columns)
    column_lines = ['Left A: 101', 'Left B: 102', 'Right A: 201', 'Right B: 202']
    for i, line in enumerate(column_lines):
        d.text((40 + (i//2)*700, 50+(i%2)*100), line, font=font, fill='black')
    columns.save(FIX/'columns-en.png')
    add('columns-en', 'image', 'en', 'png')
    corpus[-1].update(reference='\n'.join(column_lines), keywords=['101','102','201','202'])
    Image.new('RGB', (500, 500), 'white').save(FIX/'blank.png')
    add('blank', 'image', 'en', 'png', expected_failure='no_text_detected')
    for name, count in [('long-scan',12), ('page-limit',13)]:
        writer = PdfWriter()
        page = PdfReader(str(FIX/'scan-en.pdf')).pages[0]
        for _ in range(count): writer.add_page(page)
        writer.write(str(FIX/f'{name}.pdf'))
        add(name, 'pdf', 'en', 'pdf', expected_pages=count, expected_mode='ocr')
    writer = PdfWriter()
    writer.add_page(PdfReader(str(FIX/'text-en.pdf')).pages[0])
    writer.add_page(PdfReader(str(FIX/'scan-zh.pdf')).pages[0])
    writer.add_page(PdfReader(str(FIX/'scan-en.pdf')).pages[0])
    writer.write(str(FIX/'mixed.pdf'))
    add('mixed', 'pdf', 'en', 'pdf', expected_pages=3, reference_scope_override='first_unit')
    # Same-page mixed content: a text layer must not hide the lower image region.
    c = canvas.Canvas(str(FIX/'mixed-page.pdf'), pagesize=(700, 600), invariant=1)
    c.setFont('Helvetica', 18)
    c.drawString(20, 550, 'Native text before image')
    c.drawImage(str(FIX/'image-zh.png'), 0, 200, width=700, height=210)
    c.save()
    add('mixed-page', 'pdf', 'zh', 'pdf', expected_pages=1, reference_scope_override='contains_lines')
    writer = PdfWriter()
    writer.add_page(PdfReader(str(FIX/'text-en.pdf')).pages[0])
    writer.encrypt('prototype-password')
    writer.write(str(FIX/'encrypted.pdf'))
    add('encrypted', 'pdf', 'en', 'pdf', expected_failure='encrypted_pdf')
    (FIX/'corrupt.pdf').write_bytes(b'%PDF-1.7\nThis is deliberately damaged.\n')
    add('corrupt', 'pdf', 'en', 'pdf', expected_failure='corrupt_pdf')
    (FIX/'bad-image.png').write_bytes(b'not an image')
    add('bad-image', 'image', 'en', 'png', expected_failure='image_decode')
    long_text = ['Record %03d: ORCHID continues to the next position.' % i for i in range(200)]
    (FIX/'no-toc.html').write_text('<meta charset="utf-8"><article>'+''.join('<p>'+x+'</p>' for x in long_text)+'</article>', encoding='utf-8')
    add('no-toc', 'html', 'en', 'html')
    corpus[-1].update(reference='\n'.join(long_text), keywords=['Record 199'])
    for name, status in [('denied',403),('missing',404),('interrupted',200)]:
        corpus.append(dict(id=name, kind='html', language='en', url=f'{BASE}/{name}', source='injected HTTP failure', expected_failure=name))
    for lang, filename in [('zh','ch_en_num.jpg'),('en','en.jpg')]:
        corpus.append(dict(id=f'public-image-{lang}', kind='image', language=lang,
          url=f'https://raw.githubusercontent.com/RapidAI/RapidOCR/{RAPID_COMMIT}/python/tests/test_files/{filename}',
          source=f'RapidOCR official test fixture at {RAPID_COMMIT}', reference_scope='manual_snippets', keywords=[]))
    corpus.extend([
      dict(id='public-html-en',kind='html',language='en',url='https://example.com/',source='public URL',reference='Example Domain',reference_scope='contains_lines',keywords=['Example Domain']),
      dict(id='public-html-zh',kind='html',language='zh',url='https://www.gov.cn/guoqing/guoqi/',source='public URL',reference_scope='manual_review',keywords=['国旗']),
      dict(id='public-js-en',kind='js',language='en',url='https://quotes.toscrape.com/js/',source='public JS demo',ready_selector='.quote .text',reference_scope='manual_review',keywords=['Albert Einstein']),
      dict(id='public-text-pdf',kind='pdf',language='en',url='https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',source='W3C PDF fixture',reference='Dummy PDF file',reference_scope='whole_unit',keywords=['Dummy PDF file']),
      dict(id='public-404',kind='html',language='en',url='https://www.w3.org/cpu-web-read-prototype-missing-20260909',source='public URL',expected_failure='http_404'),
    ])
    for item in corpus:
        if 'reference_scope_override' in item: item['reference_scope'] = item.pop('reference_scope_override')
        if item['url'].startswith(BASE):
            path = FIX/item['url'].rsplit('/',1)[-1]
            if path.exists(): item['fixture_sha256'] = sha(path.read_bytes())
    save(ROOT/'corpus.json', corpus)
    packages = sorted((d.metadata['Name'],d.version) for d in md.distributions())
    (ROOT/'requirements.lock').write_text('\n'.join(f'{n}=={v}' for n,v in packages)+'\n',encoding='utf-8')
    with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,r'HARDWARE\DESCRIPTION\System\CentralProcessor\0') as key:
        cpu = winreg.QueryValueEx(key,'ProcessorNameString')[0]
    save(ROOT/'environment.json', dict(platform=platform.platform(),python=platform.python_version(),cpu=cpu,
        logical_cpus=os.cpu_count(),ram_bytes=psutil.virtual_memory().total,font=dict(path=font_path.name,sha256=font_hash),packages=dict(packages)))
    package = Path(md.distribution('rapidocr').locate_file('rapidocr'))
    catalog = yaml.safe_load((package/'default_models.yaml').read_text(encoding='utf-8'))
    models=[]
    def walk(value):
        if isinstance(value,dict):
            if 'SHA256' in value:
                path = package/'models'/value['model_dir'].rsplit('/',1)[-1]
                if path.exists():
                    actual=sha(path.read_bytes())
                    models.append(dict(file=path.name,sha256=actual,expected_sha256=value['SHA256'],verified=actual==value['SHA256'],source=value['model_dir']))
            else:
                for child in value.values(): walk(child)
    walk(catalog['onnxruntime'])
    save(ROOT/'models.json', models)
    assert len(models)==3 and all(x['verified'] for x in models)
    print(f'Prepared {len(corpus)} cases; 3 bundled model hashes verified.')


if __name__ == '__main__': main()
